apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-stack-kube-prom-prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      app: go-app
  serviceMonitorNamespaceSelector:
    any: true
