apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-app-monitor
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
